# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\signin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 463)
        MainWindow.setStyleSheet("background-color: rgb(37, 4, 71);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 281, 41))
        self.label.setStyleSheet("font: 48pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 111, 31))
        self.label_2.setStyleSheet("font: 24pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 101, 31))
        self.label_3.setStyleSheet("font: 24pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 110, 221, 31))
        self.lineEdit.setStyleSheet("font: 700 9pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 170, 221, 31))
        self.lineEdit_2.setStyleSheet("font: 700 9pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setEchoMode(QtCore.Qt.QLineEdit::EchoMode::Password)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 230, 75, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setTabletTracking(True)
        self.pushButton.setStyleSheet("background-color: rgb(0, 181, 0);\n"
"font: 12pt \"Mongolian Baiti\";\n"
"color: rgb(249, 255, 185);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 230, 75, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setMouseTracking(True)
        self.pushButton_2.setTabletTracking(True)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 181, 0);\n"
"font: 12pt \"Mongolian Baiti\";\n"
"color: rgb(249, 255, 185);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 380, 121, 21))
        self.label_4.setStyleSheet("font: 13pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 370, 75, 31))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setMouseTracking(True)
        self.pushButton_3.setTabletTracking(True)
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 181, 0);\n"
"font: 12pt \"Mongolian Baiti\";\n"
"color: rgb(249, 255, 185);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 270, 91, 21))
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_5.setMouseTracking(True)
        self.label_5.setTabletTracking(True)
        self.label_5.setStyleSheet("font: 13pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setTextInteractionFlags(QtCore.Qt.Qt::TextInteractionFlag::TextBrowserInteraction)
        self.label_5.setObjectName("label_5")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(10, 230, 151, 16))
        self.radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton.setStyleSheet("font: 13pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.radioButton.setObjectName("radioButton")
        self.lineEdit_2.raise_()
        self.lineEdit.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.radioButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.radioButton)
        MainWindow.setTabOrder(self.radioButton, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sign in"))
        self.label.setText(_translate("MainWindow", "Welcome back"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.pushButton.setText(_translate("MainWindow", "Sign in"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel"))
        self.label_4.setText(_translate("MainWindow", "Don\'t have an account? "))
        self.pushButton_3.setText(_translate("MainWindow", "Sign up"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0078d7;\">Forgot Password?</span></a></p></body></html>"))
        self.radioButton.setText(_translate("MainWindow", "Keep me signed in."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
