# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtWidgets import QLineEdit, QAbstractSpinBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(441, 500)
        MainWindow.setStyleSheet("background-color: rgb(37, 4, 71);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 20, 311, 51))
        self.label.setStyleSheet("font: 48pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 111, 31))
        self.label_2.setStyleSheet("font: 24pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 101, 31))
        self.label_3.setStyleSheet("font: 24pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 110, 221, 31))
        self.lineEdit.setStyleSheet("font: 700 9pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 170, 221, 31))
        self.lineEdit_2.setStyleSheet("font: 700 9pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setEchoMode(QLineEdit.EchoMode.Password)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 410, 111, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setTabletTracking(True)
        self.pushButton.setStyleSheet("background-color: rgb(0, 181, 0);\n"
"font: 12pt \"Mongolian Baiti\";\n"
"color: rgb(249, 255, 185);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 410, 75, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setMouseTracking(True)
        self.pushButton_2.setTabletTracking(True)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 181, 0);\n"
"font: 12pt \"Mongolian Baiti\";\n"
"color: rgb(249, 255, 185);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 230, 191, 31))
        self.label_4.setStyleSheet("font: 24pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(210, 230, 221, 31))
        self.lineEdit_3.setStyleSheet("font: 700 9pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_3.setEchoMode(QLineEdit.EchoMode.Password)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 290, 141, 31))
        self.label_5.setStyleSheet("font: 24pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.label_5.setObjectName("label_5")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(210, 280, 221, 41))
        self.dateEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateEdit.setMouseTracking(True)
        self.dateEdit.setTabletTracking(True)
        self.dateEdit.setStyleSheet("font: 24pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.dateEdit.setFrame(True)
        self.dateEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dateEdit.setAccelerated(True)
        self.dateEdit.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.dateEdit.setProperty("showGroupSeparator", True)
        self.dateEdit.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.dateEdit.setMinimumDate(QtCore.QDate(1900, 9, 14))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 350, 61, 31))
        self.label_6.setStyleSheet("font: 24pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(210, 350, 221, 31))
        self.lineEdit_4.setStyleSheet("font: 700 9pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhEmailCharactersOnly)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(10, 400, 201, 16))
        self.checkBox.setStyleSheet("font: 11pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 420, 191, 21))
        self.label_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_7.setMouseTracking(True)
        self.label_7.setTabletTracking(True)
        self.label_7.setStyleSheet("font: 11pt \"Gabriola\";\n"
"color: rgb(255, 249, 61);")
        self.label_7.setOpenExternalLinks(True)
        self.label_7.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.label_7.setObjectName("label_7")
        self.checkBox.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.dateEdit.raise_()
        self.label_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 441, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.dateEdit)
        MainWindow.setTabOrder(self.dateEdit, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Create Account"))
        self.label.setText(_translate("MainWindow", "Create Account"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.pushButton.setText(_translate("MainWindow", "Create Account"))
        self.pushButton_2.setText(_translate("MainWindow", "Back"))
        self.label_4.setText(_translate("MainWindow", "Confirm Password:"))
        self.label_5.setText(_translate("MainWindow", "Date of Birth:"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "dd MMMM yyyy"))
        self.label_6.setText(_translate("MainWindow", "Email:"))
        self.checkBox.setText(_translate("MainWindow", "By signing up, you agree to our"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0078d7;\">Terms, Privacy Policy and Cookies Policy.</span></a></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
